#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

REQUIRE_EDIT_GRAPH="${REQUIRE_EDIT_GRAPH:-1}" \
REQUIRE_PREVIEW="${REQUIRE_PREVIEW:-1}" \
REQUIRE_HISTOGRAM="${REQUIRE_HISTOGRAM:-1}" \
EXPECTED_MIN_EDIT_GRAPH_NODES="${EXPECTED_MIN_EDIT_GRAPH_NODES:-20}" \
EXPECTED_MIN_EDIT_GRAPH_SUBGRAPHS="${EXPECTED_MIN_EDIT_GRAPH_SUBGRAPHS:-5}" \
SKIP_SERVER_TESTS="${SKIP_SERVER_TESTS:-1}" \
SKIP_BUILD="${SKIP_BUILD:-1}" \
KEEP_ARTIFACTS="${KEEP_ARTIFACTS:-1}" \
EXPECTED_DELTA="${EXPECTED_DELTA:-0.7}" \
"$SCRIPT_DIR/agent_exposure_smoke.sh"
