#!/bin/bash
#   This file is part of darktable,
#   Copyright (C) 2012-2013 Jean-Sébastien Pédron.
#   Copyright (C) 2013 johannes hanika.
#   Copyright (C) 2016 Tobias Ellinghaus.
#   Copyright (C) 2020 Heiko Bauke.
#   
#   darktable is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   darktable is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with darktable.  If not, see <http://www.gnu.org/licenses/>.
#   
set -e

scriptname=$(basename $0)
scriptdir=$(cd $(dirname $0) && pwd)

. "$scriptdir/subr.sh"

# --------------------------------------------------------------------
# Read command line arguments.
# --------------------------------------------------------------------

usage() {
	cat <<EOF
$scriptname <original RAW image> [<jpeg version>]
EOF
}

orig_image=$1
jpeg_image=$2

# Check for required tools.
echo "===> Check for required tools"
missing_tool=0

if ! image_export_tools_installed; then
	missing_tool=1
fi

if [ "$missing_tool" = "1" ]; then
	exit 1
fi

# Check if jpeg export exists.
if [ -z "$jpeg_image" ]; then
	jpeg_image="${image%.*}-large.jpg"
	export_large_jpeg "$orig_image" "$jpeg_image"
fi

check_exposure "$orig_image" "$jpeg_image"
